apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Monitoring-kubernetes-cluster1
  region: us-east-2

nodeGroups:
  - name: ng-11
    instanceType: t2.micro
    desiredCapacity: 10
  - name: ng-21
    instanceType:  t2.micro
    desiredCapacity: 10
 